id: ad34761115204e5492915e848e5713bf
initial_creation_type: ocr
source_metadata:
  volumes:
    da205e8d914349f9ad61a3a55284754e:
      base_file: v076.txt
      image_group_id: I1PD95922
      title: ''
      total_pages: 1517
      volume_number: 77
